### ISSUE TITLE
repository의 description 오타 수정

### ISSUE THREAD

**Issue by jo-bata** [jungseungyeo/SwiftlyNetworker#1]
- repository의 description에 자그마한 오타가 발견되어 수정 요청드립니다!
![스크린샷 2022-03-22 오후 7 05 18](https://user-images.githubusercontent.com/36880294/159456569-39db03da-dcfc-4aa0-897a-f04402ca723c.png)
  - Netowkrer => Networker

**Comment by jungseungyeo** [comment]
![image](https://user-images.githubusercontent.com/32052386/159459993-64026163-7802-4533-8c05-2153e94e5a93.png)
